account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    CustomLoginView, 
    RegisterUserView, 
    CustomLogoutView, 
    EditProfileView, 
    ChangePasswordView
)
from django.views.generic import TemplateView


app_name = 'account'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("profil/", EditProfileView.as_view(), name='edit_profile'),
    path('c/', ChangePasswordView.as_view(template_name = 'account/change_password.html'), name='change_password'),
]

main/urls.py
from django.urls import path
from .views import HomeView, CreateSavingView, DetailSavingView, UpdateSavingVIew, DeleteSavingView
from . import services
app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home' ),
    path('create/',CreateSavingView.as_view(), name='create' ),
    path('detail/<slug:slug>', DetailSavingView.as_view(), name='detail_saving'),
    path('update/<slug:slug>', UpdateSavingVIew.as_view(), name='update'),
    path('detail/<slug:slug>/download-xlsx', services.convert_saving_log_to_excel, name='export_to_excel' ),
    path('delete/<slug:slug>',DeleteSavingView.as_view(), name='delete' )
    
]

savings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('landing/', TemplateView.as_view(template_name = 'landing.html')),
    path('account/', include('account.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser) : 
    last_name = None
    first_name = None

    def __str__(self):
        return self.username

account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User

class CustomUserCreationForm(UserCreationForm) :
    class Meta : 
        model = User
        fields = ['username', 'password1', 'password2']

class EditProfileForm(UserChangeForm) :
    class Meta : 
        model = User
        fields = ['username', 'email']

account/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView
from django.views.generic.edit import FormView
from .forms import CustomUserCreationForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
from django.contrib import messages

class RedirectAuthenticatedUserMixin : 
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated : 
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)
    

class CustomLoginView(RedirectAuthenticatedUserMixin, LoginView) :
    template_name = 'account/login.html'
    next_page = '/'


class CustomLogoutView(LogoutView) :
    success_url = 'account/login/'


class RegisterUserView(RedirectAuthenticatedUserMixin, CreateView) :
    form_class = CustomUserCreationForm
    template_name = 'account/register.html'

    def get_success_url(self):
        self.success_url = reverse_lazy('account:login')
        return super().get_success_url()
    

class EditProfileView(UpdateView) :
    form_class = EditProfileForm
    template_name = 'account/profile.html'
    success_url = reverse_lazy('main:home')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Profil berhasil di perbarui')
        return super().form_valid(form)
    

class ChangePasswordView(LoginRequiredMixin, FormView):
    form_class = PasswordChangeForm
    template_name = 'account/change_password.html'
    success_url = reverse_lazy('account:login')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  
        return kwargs

    def form_valid(self, form):
        form.save()
        print('pacak')
        return super().form_valid(form)
    

templates/account.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/dist/styles.css" %}?{% now 'U' %}">
</head>
<body class="bg-primary">
    {% block body %}
    
    {% endblock body %}

    {% block end_body %}
    {% endblock end_body %}
</body>
</html>

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="google" content="notranslate">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static "css/dist/styles.css" %}?{% now 'U' %}">
	<style>
		{% block style %}{% endblock style %}
	</style>
</head>
<body class="font-primary bg-primary text-white" style="font-family: consolas;">
	<div class="h-14">
		<nav class="fixed w-screen px-3 flex justify-center py-1 ">
			<div class="flex  items-center  justify-between w-11/12 ">
				<a href="{% url "main:home" %}" class="text-white font-logo text-3xl ">MySavings</a>
				<a href="{% url "account:edit_profile" %}" class="text-xl" >{{ user }}</a>
			</div>
		</nav>
	</div>
	{% block body %}{% endblock body %}
	<div class="px-2 md:px-4">
	</div>

{% block end_body %}{% endblock end_body %}

</body>
</html>

templates/landing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/dist/styles.css" %}">
</head>
<body class="h-screen bg-[#1e3350] flex items-center justify-center px-4 font-primary">
    <div class="text-center">
      <h1 class="text-white text-5xl md:text-8xl font-bold font-logo  mb-10"  style=" text-shadow: -2px 6px 1px rgba(255,255,255,0.25);">
        MySavings
      </h1>
      <div class="flex justify-center gap-4">
        <a href="{% url "account:login" %}"
          class="border border-[#0F6BAE] text-[#0F6BAE] px-6 py-2 rounded-md hover:bg-[#0F6BAE] hover:text-white transition duration-300">
          Login
        </a>
        <a href="{% url "account:register" %}"
          class="bg-[#0F6BAE] text-white px-6 py-2 rounded-md hover:bg-blue-800 transition duration-300">
          Sign up
        </a>
      </div>
    </div>
  </body>
</html>