main/urls.py
from django.urls import path
from .views import HomeView, CreateSavingView, DetailSavingView, UpdateSavingVIew, DeleteSavingView
from . import services
app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home' ),
    path('create/',CreateSavingView.as_view(), name='create' ),
    path('detail/<slug:slug>', DetailSavingView.as_view(), name='detail_saving'),
    path('update/<slug:slug>', UpdateSavingVIew.as_view(), name='update'),
    path('detail/<slug:slug>/download-xlsx', services.convert_saving_log_to_excel, name='export_to_excel' ),
    path('delete/<slug:slug>',DeleteSavingView.as_view(), name='delete' )
    
]

savings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('landing/', TemplateView.as_view(template_name = 'landing.html')),
    path('account/', include('account.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

main/models.py
from django.db import models
from django.utils.text import slugify
from account.models import User
from decimal import Decimal


# Create your models here.
class Saving(models.Model) : 
    user = models.ForeignKey(User ,on_delete=models.CASCADE, related_name='saving')
    title = models.CharField(max_length=40)
    description = models.TextField(max_length=270, blank=True)
    target = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    collected = models.DecimalField(max_digits=12, decimal_places=2, blank=True, default=0)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)
    deadline = models.DateField(auto_now=False, null=True, blank=True)
    # link = 
    slug = models.SlugField(blank=True)

    def save(self) :
        self.slug = slugify(self.title)
        return super().save()

    class Meta : 
        db_table = 'saving'

    def __str__(self):
        return self.title
    

class SavingLogs(models.Model) :
    saving = models.ForeignKey(Saving, on_delete=models.CASCADE, related_name='saving_entries')
    nominal = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    total = models.DecimalField(max_digits=12, decimal_places=2, default=Decimal('0.00'))
    description = models.TextField(max_length=270, blank=True)
    status = models.CharField(max_length=7)
    datetime = models.DateTimeField(auto_now_add=True)

    class Meta : 
        db_table = 'saving_logs'

main/forms.py
from django import forms
from .models import Saving, SavingLogs
from decimal import Decimal

class SavingLogsForm(forms.ModelForm) :
    class Meta : 
        model = SavingLogs
        fields = ['nominal', 'description']

        widgets = {
            'nominal' : forms.NumberInput(
                attrs= {
                    'placeholder' : 'Nominal',
                
                }
            ),
            'description' : forms.Textarea(
                attrs= {
                    'placeholder' : 'Deskripsi'
                }
            )
        }

    def __init__(self, *args, **kwargs) :
        self.saving = kwargs.pop('saving')
        self.collected = kwargs.pop('collected')
        super().__init__(*args, **kwargs)

    def clean_nominal(self):
        nominal = self.cleaned_data.get("nominal")
        log_saving = self.saving.saving_entries.order_by('-datetime').first() 
        if log_saving :
            total = log_saving.total
            if self.data.get('action') == 'ambil' and nominal > total :
                print(self.cleaned_data)
                raise forms.ValidationError('Total tabungan anda tidak cukup untuk diambil')
        else : 
            if self.data.get('action') == 'ambil' and not self.collected :
                raise forms.ValidationError('Total tabungan anda tidak cukup untuk diambil')
            
        return nominal
    

main/views.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .models import Saving, SavingLogs
from  .forms import SavingLogsForm
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages

# Create your views here.
class HomeView(LoginRequiredMixin, ListView) :
    template_name = 'main/home.html'
    context_object_name = 'savings'

    def get_queryset(self):
        return self.request.user.saving.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        return context


class CreateSavingView(LoginRequiredMixin, CreateView) :
    template_name = 'main/saving_form.html'
    model = Saving
    fields = ['description', 'target', 'title', 'deadline', 'collected']
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, 'Tabungan berhasil dibuat')
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        context['title_template'] = 'Buat tabungan'
        context['button_name'] = 'Buat'
        return context


class DetailSavingView(LoginRequiredMixin, FormMixin, DetailView) :
    template_name = 'main/detail_saving.html'    
    model = Saving
    form_class = SavingLogsForm

    def form_valid(self, form, status, nominal):
        form.instance.saving = self.get_object()
        form.instance.status = status
        if status == 'Masuk' :
            form.instance.total = self.get_total_nominal() + nominal 
        elif status == 'Keluar' :
            if self.get_total_nominal() - nominal > 0 :
                form.instance.total = self.get_total_nominal() - nominal
            else :
                form.instance.total = 0
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        logs = self.get_object().saving_entries.all()
        context = super().get_context_data(**kwargs)
        context['logs'] = logs
        context['collected'] = self.get_total_nominal()
        context['status'] = logs.order_by('-datetime').first() 
        context['gap'] = self.get_object().target - self.get_total_nominal()
        return context 

    def post(self, request, *args, **kwargs) :
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid() :
            action = self.request.POST.get('action')
            nominal = int(self.request.POST.get('nominal'))
            if action == 'setor' : 
                return self.form_valid(form, 'Masuk', nominal)
            else : 
                return self.form_valid(form, 'Keluar', nominal)
        else : 
            return self.form_invalid(form)
        
    # Custom Method 
    def get_total_nominal(self) :
        count = 0
        saving = self.get_object()
        count = saving.collected    
        for nominal in saving.saving_entries.all() : 
            if nominal.status == 'Masuk' :
                count += nominal.nominal
            elif nominal.status == 'Keluar' : 
                count -= nominal.nominal
                if count < 0 :
                    count = 0
        return count 
    
    def get_success_url(self):
        self.success_url = reverse_lazy('main:detail_saving', kwargs = {'slug' : self.kwargs['slug']})
        return super().get_success_url()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['saving'] = self.get_object()
        kwargs['collected'] = self.get_total_nominal()
        return kwargs

class UpdateSavingVIew(LoginRequiredMixin, UpdateView) :
    model = Saving
    fields = ['description', 'target', 'title', 'deadline']
    template_name = 'main/saving_form.html'
    
    def get_success_url(self):
        self.success_url = reverse_lazy('main:detail_saving', kwargs = {'slug' : self.kwargs['slug']})
        return super().get_success_url()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['button_name'] = 'Selesai'
        context['title_template'] = 'Edit tabungan'
        return context

class DeleteSavingView(LoginRequiredMixin, DeleteView) :
    model = Saving
    success_url = reverse_lazy('main:home')

main/templates/main/detail_saving.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block style %}
.no-arrow::-webkit-inner-spin-button, 
.no-arrow::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.no-arrow {
  -moz-appearance: textfield;
}
{% endblock style %}





{% block body %}
    <div class="px-2 md:px-4">
        <header class="mb-4">
            <h1 class="text-4xl md:text-5xl font-bold flex items-center space-x-2"> 
                <span>{{ saving.title }}</span> 
            </h1>
            <p class="text-sm text-gray-300 mt-1">{{ saving.description }}</p>
        </header>
        <div class="flex mb-3 gap-4">
            <a href="{% url "main:update" saving.slug %}" class="flex border-2 border-solid border-[#3B82F6] rounded-lg text-[#3B82F6] max-w-10 sm:max-w-52 w-full  justify-center items-center gap-2 py-1   hover:bg-[#3B82F6]/20 duration-150 ">
                <svg class="w-5 h-5 sm:h-6 sm:w-6" xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 -960 960 960" width="20px" fill="#3B82F6"><path d="M200-200h57l391-391-57-57-391 391v57Zm-80 80v-170l528-527q12-11 26.5-17t30.5-6q16 0 31 6t26 18l55 56q12 11 17.5 26t5.5 30q0 16-5.5 30.5T817-647L290-120H120Zm640-584-56-56 56 56Zm-141 85-28-29 57 57-29-28Z"/></svg>
                <span class="text-md hidden sm:flex" >Edit Tabungan</span>
            </a>
            <div class="bg-[#3B82F6] text-white rounded-lg w-full md:w-1/2 flex items-center justify-center  font-bold target progress-bar">Rp  <span class="nominal target">{{ saving.target }}</span></div>
        </div>
        <table class="text-sm mb-3">
            <tr class="text-[#40C4FF]">
                <td>Deadline</td>
                <td>: 
                    {% if saving.deadline %}
                        {{ saving.deadline }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        
                <tr class="text-[#FFAA00]">
                    <td>Gap</td>
                    <td>: Rp  <span class="nominal">{{ gap }}</span></td>
                </tr>
                <tr class="text-[#BA68C8]">
                    <td>Terkumpul</td>
                    <td>: Rp <span class="nominal saving-now">{{ collected }}</span></td>
                </tr>
                <tr class="text-[#]">
                    <td>Status</td>
                    <td>: 
                        {% if logs %}
                            {% if status.status == 'Masuk' %}
                                <span class="text-[#00FF08]">+ Rp 
                                    <span class="nominal">{{ status.nominal }}</span>/ {{ status.datetime }}
                                </span>
                            {% else %}
                                <span class="text-red-600">- Rp 
                                    <span class="nominal">{{ status.nominal }}</span>/ {{ status.datetime }}
                                </span>
                            {% endif %}
                        {% else %}
                            -
                        {% endif %}
                    
                    </td>
                </tr>
                

            
        </table>
        <form method="POST" class="mb-6 max-w-96">
            {% csrf_token %}
            <div class="mb-3 flex flex-col">
                <div class="mb-2">
                    {{ form.nominal|add_class:"no-arrow  w-full  p-2 bg-white text-gray-800 rounded" }}
                    <span class="text-red-500 text-[11px]">{{ form.errors.nominal.0 }}</span>
                </div>
                {{ form.description|add_class:"w-full  p-2 bg-white text-gray-800 rounded h-24" }}
            </div>
            <div class="flex space-x-2">
                <button  name="action" value="ambil"  class="bg-red-500 w-full text-white px-4 py-2 rounded hover:bg-red-600 transition">Ambil</button>
                <button name="action" value="setor" class="bg-green-500 w-full text-white px-6 py-2 rounded hover:bg-green-600 transition">Setor</button>
            </div>
        </form>
        <div class="flex justify-end mb-4">
            <a href="{% url "main:export_to_excel" saving.slug %}" class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition">Export .xlsx</a>
        </div>
        <div class="overflow-x-auto rounded-lg">
            <table class="min-w-full bg-gray-800">
                <thead>
                    <tr class="bg-gray-600 text-left ">
                        <th class="py-3 px-4">No</th>
                        <th class="py-3 px-4 w-56">Tanggal</th>
                        <th class="py-3 px-4">Status</th>
                        <th class="py-3 px-4">Nominal</th>
                        <th class="py-3 px-4">Deskripsi</th>
                        <th class="py-3 px-4">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logs  %}
                        <tr class="border-b border-gray-600 hover:bg-gray-700 cursor-pointer log-row">
                            <td class="py-3 px-4">{{ forloop.counter }}</td>
                            <td class="py-3 px-4 max-w-xs truncate">{{ log.datetime }}</td>
                            {% if log.status == 'Masuk' %}
                                <td class="py-3 px-4 text-green-400">{{ log.status }}</td>
                            {% else %}
                                <td class="py-3 px-4 text-red-500">{{ log.status }}</td>
                            {% endif %}
                            <td class="py-3 px-4 max-w-xs truncate">Rp <span class="nominal">{{ log.nominal }}</span></td>
                            <td class="py-3 px-4 max-w-xs truncate">
                                {% if log.description != '' %}
                                    {{ log.description }}
                                {% else %} 
                                    -
                                {% endif %}

                            </td>
                            <td class="py-3 px-4 max-w-xs truncate">Rp  <span class="nominal">{{ log.total }}</span></td>
                        </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </div> 
        <div class="flex justify-between mt-10 mb-10 items-center  h-14 px-6  rounded-lg border-2 border-red-500/65">
            <h3>Hapus Tabungan ini</h3>
            <button class="btn-delete-confirm  border-2 border-red-500/65 text-red-500 w-24 py-0.5  rounded-md bg-red-500/15">Hapus</button>

        </div>       
    </div>
    

    {% comment %} modal {% endcomment %}
    <div class="modal fixed top-0 left-0  w-screen h-screen z-50 hidden">
        <div class="bg-black/75 h-full w-full  flex justify-center items-center">
            <div class="modal-container bg-gray-700 w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
                  <div class="modal-content py-4 text-left px-6">
                        <div class="flex justify-end items-center pb-3">
                            <div class="modal-close cursor-pointer z-50">
                                <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                                    <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
                                </svg>
                            </div>
                        </div>
                        
                        <div class="modal-body modal-detail hidden">
                            <div class="mb-4">
                                <p class="text-sm text-gray-400">ID</p>
                                <p class="font-bold  modal-field "></p>
                            </div>
                            <div class="mb-4">
                                <p class="text-sm text-gray-400">Tanggal</p>
                                <p class="font-bold  modal-field "></p>
                            </div>
                            <div class="mb-4">
                                <p class="text-sm text-gray-400">Status</p>
                                <p class="font-bold  modal-field text-red-600 "></p>
                            </div>
                            <div class="mb-4">
                                <p class="text-sm text-gray-400">Nominal</p>
                                <p class="font-bold  modal-field "></p>
                            </div>
                            <div class="mb-4">
                                <p class="text-sm text-gray-400">Deskripsi</p>
                                <p class="font-bold  modal-field w-2"></p>
                            </div>
                            <div class="mb-4">
                                <p class="text-sm text-gray-400">Total Setelah Transaksi</p>
                                <p class="font-bold  modal-field "></p>
                            </div>
                        </div>
                        
                        <div class="modal-delete mb-7 mt-3 gap-3 hidden">
                            <div class="flex items-center  ">
                                <svg class="w-8 h-8 fill-red-500/80 "    xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#FF0000"><path d="m40-120 440-760 440 760H40Zm138-80h604L480-720 178-200Zm302-40q17 0 28.5-11.5T520-280q0-17-11.5-28.5T480-320q-17 0-28.5 11.5T440-280q0 17 11.5 28.5T480-240Zm-40-120h80v-200h-80v200Zm40-100Z"/></svg>
                                <span>Yakin Mengahapus Tabungan ini ? </span>
                            </div>
                        </div>
                       
                        <div class="flex justify-end pt-2 gap-3">
                            <button class="modal-close close-button px-4 bg-gray-500 p-3 rounded-lg text-white hover:bg-gray-400">Tutup</button>
                            <form action="{% url "main:delete" saving.slug %}" method="POST"  class="modal-btn-delete hidden" >
                                {% csrf_token %}  
                                <button class="px-4 bg-red-500/70 p-3 rounded-lg text-white hover:bg-red-500">Hapus</button>

                            </form>

                        </div>
                  </div>
              </div>
        </div>
    </div>
    
{% endblock body %}

{% block  end_body %}
    <script src="{% static "main/js/detail_saving.js" %}"></script>

{% endblock end_body %}

main/templates/main/home.html
{% extends "base.html" %}
{% load static %}
{% load template_tags_saving %}


{% block body %}
    <div class=" font-primary px-3">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="mb-5 px-4 alert">
                        <div class="border-2 border-solid border-[#0FFF00] text-[#0FFF00] px-4 sm:px-8 h-12 rounded-xl bg-[#0FFF00]/10 flex items-center justify-between">
                            <div class="flex items-center gap-2 w-full sm:w-72  px-2 py-1 rounded-lg">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 hidden sm:flex" viewBox="0 -960 960 960" fill="#0FFF00">
                                    <path d="M382-240 154-468l57-57 171 171 367-367 57 57-424 424Z"/>
                                </svg>
                                <span class="text-sm sm:text-base">{{ message }}</span>
                            </div>
                            <button class="p-1 close">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 -960 960 960" fill="#0FFF00">
                                    <path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/>
                                </svg>
                            </button>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <div class=" grid grid-flow-row grid-cols-1 md:grid-cols-2 lg:grid-cols-3  2xl:grid-cols-4 gap-4">
            <div class="border-2 border-solid border-[#c6cdff] rounded-md h-72 " style=" box-shadow: 0px 4px 13px 4px rgba(198,205,255,0.25)">
                <a href="{% url "main:create" %}" class="grid justify-center h-full hover:bg-[#c6cdff]/10 duration-100">
                    <div class=" flex justify-center">
                        <svg xmlns="http://www.w3.org/2000/svg" height="180px" width="180px" viewBox="0 -960 960 960"  fill="white"><path d="M440-440H200v-80h240v-240h80v240h240v80H520v240h-80v-240Z"/></svg>
                    </div>
                    <span class="text-center text-3xl">Buat Tabungan </span>
                </a>
            </div>
         
            {% for saving in savings %}
                
                <div class="h-72 border-2 border-solid border-[#248BD6] rounded-md  hover:bg-[#248BD6]/10" style="box-shadow: 0px 4px 13px 7px rgba(36,139,214,0.25)">
                    <a href="{% url "main:detail_saving" saving.slug %}" class="w-full h-full">
                        <span class="text-sm text-[#248BD6] px-2">{{ saving.created_at }}</span>
                        <p class=" h-40 text-4xl md:text-5xl  px-2  saving_title" >{{ saving.title }} </p>
                        <div class=" mx-2 bg-[#248BD6] w-[60%]  text-center rounded-lg mb-1 ">Rp  <span class="nominal">{{ saving.target }}</span> </div>
                        <div class="px-2">
                        <table class="text-[14px] md:text-sm">
                                <tr class="text-[#40c4ff]">
                                    <td class="w-24">Deadline </td>
                                    <td>:  {{ saving.deadline }} </td>
                                </tr>
                                {% status saving.id as status %}
                                <tr>
                                    <td>Status </td>
                                    <td>:
                                        {% if status.status == 'Masuk' %}
                                            <span class="text-[#00FF08]">+ Rp  <span class="nominal">{{ status.nominal }}</span> </span> 
                                        {% elif status.status == 'Keluar' %}
                                            <span class="text-[#FF0000]">- Rp  <span class="nominal">{{ status.nominal }}</span> </span> 
                                        {% else %}
                                            -
                                        {% endif %}  
                                    </td>
                                </tr>
                                <tr class="text-[#FFAA00]">
                                    <td>Gap </td>
                                    <td>: Rp  <span class="nominal">{% gap saving.target status.total %}</span></td>
                                </tr>
                            
                        </table>
                        </div>
                    </a>
                </div> 
        
            {% endfor %}
            
            
        </div>
    </div>

{% endblock body %}

{% block end_body %}
    <script src="{% static "main/js/home.js" %}"></script>

{% endblock end_body %}

main/templates/main/saving_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block style %}
.no-arrow::-webkit-inner-spin-button, 
.no-arrow::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.no-arrow {
  -moz-appearance: textfield;
}
{% endblock style %}

{% block body %}
<div class="container mx-auto min-h-full flex items-center justify-center  p-4">
    <form class="w-full max-w-2xl bg-transparent text-white space-y-4" method="POST">
      {% csrf_token %}
      <h3 class="text-3xl font-semibold text-center">{{ title_template }}</h3>
      <div>
        <label class="block text-sm font-semibold mb-" for="id_title">Nama Tabungan</label>
      
        {{ form.title|add_class:"w-full px-3 py-2 rounded bg-white text-black placeholder-gray-400 focus:outline-none"|attr:"placeholder:Nama tabungan" }}
      </div>
  
      <div>
        <label class="block text-sm font-semibold mb-1" for="id_description">Deskripsi (opsional)</label>
        {{ form.description|add_class:"w-full h-28 px-3 py-2 rounded bg-white text-black placeholder-gray-400 focus:outline-none"|attr:"placeholder:Deskripsi (max 220)" }}
      </div>
  
      <div class="flex flex-col md:flex-row md:space-x-4 space-y-4 md:space-y-0">
        <div class="flex-1">
          <label class="block text-sm font-semibold mb-1 " for="id_target">Target</label>
          {{ form.target|add_class:"no-arrow nominal w-full px-3 py-2 rounded bg-white text-black placeholder-gray-400 focus:outline-none"|attr:"placeholder:10.000.000"}}
        </div>
        {% if title_template != 'Edit tabungan' %}
          <div class="flex-1">
            <label class="block text-sm font-semibold mb-1" for="id_collected">Terkumpul (opsional)</label>
            {{ form.collected|add_class:"no-arrow nominal w-full px-3 py-2 rounded bg-white text-black placeholder-gray-400 focus:outline-none"|attr:"placeholder:100.000" }}
          </div>
        {% endif %}
        <div class="flex-1">
          <label class="block text-sm font-semibold mb-1" for="id_deadline" >Deadline (opsional)</label>
         
          {{ form.deadline|add_class:"w-full px-3 py-2 rounded bg-white text-black focus:outline-none"|attr:"type:date" }}

        </div>
      </div>

      <div class="text-right">
        <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-semibold px-6 py-2 rounded transition">{{ button_name }}</button>
      </div>
      
    </form>
  </div>

{% endblock body %}